import { useState, useEffect } from 'react';
import { Video, Plus } from 'lucide-react';
import type { ShortsModule, ShortItem, ShortStatus } from '../types';
import { ShortCard } from './ShortCard';
import { ReviewModal } from './ReviewModal';
import { ScheduleModal } from './ScheduleModal';
import { FileBrowserModal } from './FileBrowserModal';

interface ShortsSectionProps {
    data: ShortsModule;
    onUpdate: (newData: ShortsModule) => void;
}

export const ShortsSection = ({ data, onUpdate }: ShortsSectionProps) => {
    const [reviewItem, setReviewItem] = useState<ShortItem | null>(null);
    const [scheduleItem, setScheduleItem] = useState<ShortItem | null>(null);
    const [linkVideoItem, setLinkVideoItem] = useState<ShortItem | null>(null);

    // Helper to update a specific item
    const updateItem = (id: string, updates: Partial<ShortItem>) => {
        const newItems = data.items.map(item =>
            item.id === id ? { ...item, ...updates, updatedAt: new Date().toISOString() } : item
        );
        onUpdate({ ...data, items: newItems });
    };

    const handleCreateDraft = () => {
        // Mock creating a new draft for now
        // In real flow, this might come from ShortsMaster skill
        const newId = (data.items.length + 1).toString().padStart(2, '0');
        const newItem: ShortItem = {
            id: newId,
            title: `Shorts ${newId} (Draft)`,
            description: 'Generated by Shorts Master',
            tags: [],
            scriptPath: `scripts/shorts_${newId}.md`,
            status: 'draft',
            reviewHistory: [],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        };
        onUpdate({ ...data, items: [...data.items, newItem] });
    };

    const handleReviewCriteria = (id: string) => {
        const item = data.items.find(i => i.id === id);
        if (item) {
            // If in draft, switch to script_review to indicate review in progress (optional)
            if (item.status === 'draft') {
                updateItem(id, { status: 'script_review' });
            }
            // If already in review status, just open
            setReviewItem(item); // Open modal using current item state (will re-render if data updates? No, need to be careful)
        }
    };

    // We need to keep reviewItem in sync with data if we want real-time updates while modal is open? 
    // Or just pass the ID to modal and let it find it? 
    // Let's pass the ID or derived item.
    const activeReviewItem = reviewItem ? data.items.find(i => i.id === reviewItem.id) || reviewItem : null;
    const activeScheduleItem = scheduleItem ? data.items.find(i => i.id === scheduleItem.id) || scheduleItem : null;

    const handleApprove = (id: string, stage: 'script' | 'render') => {
        const item = data.items.find(i => i.id === id);
        if (!item) return;

        const newHistory = [
            {
                timestamp: new Date().toISOString(),
                stage,
                action: 'approve' as const,
                comment: 'Approved by user'
            },
            ...item.reviewHistory
        ];

        let newStatus: ShortStatus = item.status;
        if (stage === 'script') {
            newStatus = 'draft'; // Back to draft, ready for render
        } else if (stage === 'render') {
            newStatus = 'approved'; // Ready for schedule
        }

        updateItem(id, { status: newStatus, reviewHistory: newHistory });
        setReviewItem(null);
    };

    const handleReject = (id: string, stage: 'script' | 'render', comment: string) => {
        const item = data.items.find(i => i.id === id);
        if (!item) return;

        const newHistory = [
            {
                timestamp: new Date().toISOString(),
                stage,
                action: 'reject' as const,
                comment
            },
            ...item.reviewHistory
        ];

        // Rejections generally send it back to draft for fixing
        updateItem(id, { status: 'draft', reviewHistory: newHistory });
        setReviewItem(null);
    };

    const handleStartRender = (id: string) => {
        const item = data.items.find(i => i.id === id);
        if (!item) return;

        // Optimistic update
        updateItem(id, { status: 'rendering' });

        // Emit socket event
        const socket = (window as any).socket;
        if (socket) {
            socket.emit('start-render', { shortsId: id });
        } else {
            console.error("Socket not found");
        }
    };

    const handleLinkVideo = (id: string) => {
        const item = data.items.find(i => i.id === id);
        if (item) {
            setLinkVideoItem(item);
        }
    };

    const handleFileSelected = (path: string) => {
        if (linkVideoItem) {
            // Update item with video path and set status to 'linked'
            updateItem(linkVideoItem.id, {
                status: 'linked',
                videoPath: path
            });
            setLinkVideoItem(null);
        }
    };

    const handleSchedule = (id: string) => {
        const item = data.items.find(i => i.id === id);
        if (item) {
            setScheduleItem(item);
        }
    };

    const handleSaveSchedule = (id: string, updates: Partial<ShortItem>) => {
        updateItem(id, updates);
        setScheduleItem(null);
    };

    const handleUpload = async (id: string) => {
        const item = data.items.find(i => i.id === id);
        if (!item) return;

        // Optimistic update
        updateItem(id, { status: 'uploading' });

        try {
            const response = await fetch('http://localhost:3002/shorts/upload', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ id })
            });

            const result = await response.json();

            if (!response.ok) {
                console.error("Upload failed", result);
                alert(`Upload failed: ${result.error || 'Unknown error'}`);
                // Revert status? Or keep as uploading/failed?
                // Ideally backend would update status to 'failed' and socket would push it.
                // But for safety, let's revert to previous status if we can, or just leave it.
                // The backend updates delivery_store, which triggers socket event.
                // So if backend fails BEFORE writing store, we stick in optimistic 'uploading'.
                // Ideally we should handle this better, but for now:
                updateItem(id, { status: item.status }); // Revert
            } else {
                console.log("Upload initiated successfully", result);
                // Backend will eventually finish and push 'published' status via socket
            }
        } catch (error) {
            console.error("Network error during upload", error);
            alert("Network error during upload");
            updateItem(id, { status: item.status }); // Revert
        }
    };

    // Derived stats
    const activeCount = data.items.filter(s => s.status !== 'published').length;
    const publishedCount = data.items.filter(s => s.status === 'published').length;

    // Auth State
    const [isAuth, setIsAuth] = useState(false);

    const checkAuthStatus = async () => {
        try {
            const res = await fetch('http://localhost:3002/auth/status');
            const data = await res.json();
            setIsAuth(data.authenticated);
        } catch (e) {
            console.error('Auth check failed. Is backend running?', e);
            setIsAuth(false);
        }
    };

    // Check auth status on mount using proper useEffect
    useEffect(() => {
        checkAuthStatus();

        // Focus listener to re-check after closing popup
        const onFocus = () => checkAuthStatus();
        window.addEventListener('focus', onFocus);
        return () => window.removeEventListener('focus', onFocus);
    }, []);

    const handleAuthorize = async () => {
        // Fix popup blocker: Open immediately
        const width = 600;
        const height = 800;
        const left = (window.screen.width - width) / 2;
        const top = (window.screen.height - height) / 2;

        const authWindow = window.open(
            '',
            'YouTube Auth',
            `width=${width},height=${height},left=${left},top=${top}`
        );

        if (!authWindow) {
            alert('Please allow popups for this site to authorize YouTube.');
            return;
        }

        authWindow.document.write('Loading YouTube Authorization...');

        try {
            const res = await fetch('http://localhost:3002/auth/url');
            const data = await res.json();
            if (data.url) {
                authWindow.location.href = data.url;

                // Start polling or listening for success
                const timer = setInterval(() => {
                    if (authWindow.closed) {
                        clearInterval(timer);
                        checkAuthStatus(); // Re-check status when window closes
                    }
                }, 1000);
            } else {
                authWindow.close();
            }
        } catch (e) {
            authWindow.close();
            alert('Failed to start auth flow');
        }
    };

    return (
        <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden mb-6">
            {/* Header */}
            <div className="p-4 border-b border-slate-700 flex justify-between items-center bg-slate-900/50">
                <div className="flex items-center gap-2">
                    <Video className="w-5 h-5 text-cyan-400" />
                    <h2 className="font-semibold text-white">Shorts Publisher (v2.0)</h2>
                    <span className="bg-cyan-500/20 text-cyan-300 px-2 py-0.5 rounded text-xs ml-2">
                        {activeCount} Active
                    </span>
                </div>
                <div className="flex items-center gap-4">
                    {publishedCount > 0 && (
                        <span className="text-xs text-emerald-400">
                            {publishedCount} Published
                        </span>
                    )}

                    {/* Auth Status & Button */}
                    <div className="flex items-center gap-2 mr-2">
                        {isAuth ? (
                            <div className="flex items-center gap-1.5 px-3 py-1.5 bg-green-900/30 border border-green-800 rounded-full text-xs text-green-400 select-none">
                                <div className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                                YouTube Connected
                            </div>
                        ) : (
                            <button
                                onClick={handleAuthorize}
                                className="flex items-center gap-2 px-3 py-1.5 bg-[#FF0000]/10 hover:bg-[#FF0000]/20 text-[#FF0000] hover:text-red-400 border border-[#FF0000]/30 rounded-full text-xs font-medium transition-colors"
                            >
                                <svg viewBox="0 0 24 24" className="w-4 h-4 fill-current"><path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" /></svg>
                                Link Account
                            </button>
                        )}
                    </div>

                    <button
                        onClick={handleCreateDraft}
                        className="p-1 hover:bg-slate-700 rounded transition-colors text-slate-400 hover:text-white"
                        title="Manually add draft (Debug)"
                    >
                        <Plus className="w-5 h-5" />
                    </button>
                </div>
            </div>

            {/* List */}
            <div className="p-6">
                {data.items.length === 0 ? (
                    <div className="text-center p-12 text-slate-500 italic bg-slate-900/30 rounded-xl border border-slate-700 border-dashed">
                        <p>No active Shorts drafts found.</p>
                        <p className="text-xs mt-2">Generate scripts using the Shorts Master skill to get started.</p>
                    </div>
                ) : (
                    <div className="space-y-4">
                        {data.items.map(item => (
                            <ShortCard
                                key={item.id}
                                item={item}
                                onReviewCriteria={handleReviewCriteria}
                                onStartRender={handleStartRender}
                                onLinkVideo={handleLinkVideo}
                                onSchedule={handleSchedule}
                                onUpload={handleUpload}
                                onEdit={handleSchedule}
                            />
                        ))}
                    </div>
                )}
            </div>

            {/* Modal */}
            {activeReviewItem && (
                <ReviewModal
                    item={activeReviewItem}
                    isOpen={!!reviewItem}
                    onClose={() => setReviewItem(null)}
                    onApprove={handleApprove}
                    onReject={handleReject}
                />
            )}

            {activeScheduleItem && (
                <ScheduleModal
                    item={activeScheduleItem}
                    isOpen={!!scheduleItem}
                    onClose={() => setScheduleItem(null)}
                    onSave={handleSaveSchedule}
                    mode={scheduleItem?.status === 'linked' ? 'schedule' : 'edit'}
                />
            )}

            <FileBrowserModal
                isOpen={!!linkVideoItem}
                onClose={() => setLinkVideoItem(null)}
                onSelect={handleFileSelected}
            />
        </div>
    );
};
